### ISSUE TITLE
Dockerfile does not align with start-it.sh

### ISSUE THREAD

**Issue by bram-pramono** [db30/act-r-container#4]
Hi,

I was trying to run the available docker container, but there are issues with rights of creating folder in the container itself. I've identified the problems and have some suggestions to fix it. However, I couldn't push my fix branch. So, I'm providing here the patch for the fix.
[fix-docker.txt](https://github.com/db30/act-r-container/files/8852217/fix-docker.txt)

**Comment by db30** [comment]
Can you provide me with more details about how you were running it (docker version, OS, etc)? The current code works on all the machines I'm using as well as through mybinder and play-with-docker, so before I change anything I'd like to be able to recreate the problem.

**Comment by bram-pramono** [comment]
Here you go.
![system-info](https://user-images.githubusercontent.com/7666863/172586525-8492a6cc-1f35-453a-a2fb-e1555dfd1c05.png)

I tried mybinder as well without a problem. That's is indeed strange. I see a conflicting command between the Dockerfile and the start-it.sh. In the Dockerfile, the folder actr7.x/tutorial is moved to actr7.x/original-tutorial, while the start-it.sh expects that  actr7.x/tutorial is available to be moved to actr7.x/original-tutorial, which caused the problem on my computer. I don't understand what is the idea behind moving actr7.x/tutorial to actr7.x/original-tutorial and vice versa in both Dockerfile and start-it.sh. That's why I just copy tutorial to original-tutorial insted of moving them.

Btw, I did make a mistake of replacing the 3 'RUN chmod 777' commands from mv to cp. You can ignore these changes.

Let me know if you need more info.

**Comment by db30** [comment]
The start-it.sh isn't copying the tutorial directory to original-tutorial, it's copying original-tutorial to tutorial.  The -t flag indicates the target.  That is done because the tutorial directory is a virtual one so that the files live outside of the container and persist across runs so one can complete the tutorial in multiple sessions.

When you run it, are you including the virtual drive specification as included in the readme?

**Comment by bram-pramono** [comment]
Thanks for keep responing. I've found out the problem I was facing. I did run the command as you have specified in the README.md. However, I didn't create the target folder ~/act-r-tutorial beforehand. Therefore, that folder is owned by root user. After I ran chown, the command you provided worked nicely.

**Comment by db30** [comment]
You're welcome, and thanks for following up.  I'll update the readme to note that potential issue.  Based on the Docker docs it says it will create it automatically if it doesn't exist and I assumed it would be with the user as owner instead of root.
